using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TennisBole
{
    public static partial class IOCConverter
    {
        private static readonly string[] CountryNames =
        {
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Bermuda",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, Dem Rep",
            "Cook Islands",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor (Timor-Leste)",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guam",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Korea, North",
            "Korea, South",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Morocco",
            "Mozambique",
            "Burma",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine, Occupied Territories",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Romania",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vietnam",
            "Virgin Islands",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        };
        private static readonly string[] NationalCodes =
        {
            "AFG",
            "ALB",
            "ALG",
            "ASA",
            "AND",
            "ANG",
            "ANT",
            "ARG",
            "ARM",
            "ARU",
            "AUS",
            "AUT",
            "AZE",
            "BAH",
            "BRN",
            "BAN",
            "BAR",
            "BLR",
            "BEL",
            "BIZ",
            "BER",
            "BEN",
            "BHU",
            "BOL",
            "BIH",
            "BOT",
            "BRA",
            "IVB",
            "BRU",
            "BUL",
            "BUR",
            "BDI",
            "CAM",
            "CMR",
            "CAN",
            "CPV",
            "CAY",
            "CAF",
            "CHA",
            "CHI",
            "CHN",
            "COL",
            "COM",
            "CGO",
            "COD",
            "COK",
            "CRC",
            "CIV",
            "CRO",
            "CUB",
            "CYP",
            "CZE",
            "DEN",
            "DJI",
            "DMA",
            "DOM",
            "TLS",
            "ECU",
            "EGY",
            "ESA",
            "GEQ",
            "ERI",
            "EST",
            "ETH",
            "FIJ",
            "FIN",
            "FRA",
            "GAB",
            "GAM",
            "GEO",
            "GER",
            "GHA",
            "GRE",
            "GRN",
            "GUM",
            "GUA",
            "GUI",
            "GBS",
            "GUY",
            "HAI",
            "HON",
            "HKG",
            "HUN",
            "ISL",
            "IND",
            "INA",
            "IRI",
            "IRQ",
            "IRL",
            "ISR",
            "ITA",
            "JAM",
            "JPN",
            "JOR",
            "KAZ",
            "KEN",
            "PRK",
            "KOR",
            "KUW",
            "KGZ",
            "LAO",
            "LAT",
            "LIB",
            "LES",
            "LBR",
            "LBA",
            "LIE",
            "LTU",
            "LUX",
            "MKD",
            "MAD",
            "MAW",
            "MAS",
            "MDV",
            "MLI",
            "MLT",
            "MTN",
            "MRI",
            "MEX",
            "FSM",
            "MDA",
            "MON",
            "MGL",
            "MAR",
            "MOZ",
            "MYA",
            "NAM",
            "NRU",
            "NEP",
            "NED",
            "AHO",
            "NZL",
            "NCA",
            "NIG",
            "NGR",
            "NOR",
            "OMA",
            "PAK",
            "PLW",
            "PLE",
            "PAN",
            "PNG",
            "PAR",
            "PER",
            "PHI",
            "POL",
            "POR",
            "PUR",
            "QAT",
            "ROM",
            "ROU",
            "RUS",
            "RWA",
            "SKN",
            "LCA",
            "VIN",
            "SAM",
            "SMR",
            "STP",
            "KSA",
            "SEN",
            "SCG",
            "SEY",
            "SLE",
            "SIN",
            "SVK",
            "SLO",
            "SOL",
            "SOM",
            "RSA",
            "ESP",
            "SRI",
            "SUD",
            "SRB",
            "SWZ",
            "SWE",
            "SUI",
            "SYR",
            "TPE",
            "TJK",
            "TAN",
            "THA",
            "TOG",
            "TGA",
            "TRI",
            "TUN",
            "TUR",
            "TKM",
            "UGA",
            "UKR",
            "UAE",
            "GBR",
            "USA",
            "URU",
            "UZB",
            "VAN",
            "VEN",
            "VIE",
            "ISV",
            "YEM",
            "ZAM",
            "ZIM"
        };
        private static Dictionary<string, string> NameToCode = null;
        private static Dictionary<string, string> CodeToName = null;
    }
}
